// AUTO-GENERATED by 70-tools/scripts/llm-registry/gen-roso-entries.mjs
// Source manifest: 90-docs/baien/roso-models.jsonl
// Do not edit by hand — re-run the codegen to refresh.
// Per ADR-2605242000 (Bonsai-pattern 1-bit siblings) + ADR-2605241900 (edge invariant).

import type { ModelDef } from "./llm-model-types.js";

export const ROSO_MODEL_REGISTRY: Record<string, ModelDef> = {
  // roso-bonsai-1bit from Zyphra/Zamba2-7B (bonsai-w1, phase A)
  // packed: 1 GB | RAM @4k: 1.2875 GB | RAM @16k: 1.4 GB
  // edge-invariant pass: true
  // recovery: (phase A, no recovery)
  // quantized weights: /tmp/roso-smoke-out/sibling-00-Zyphra__Zamba2-7B
  // decision: commit — review before flipping available=true
  "roso-zamba2-7b": {
    cfModel: "huggingface:Zyphra/Zamba2-7B",
    huggingfaceModel: "Zyphra/Zamba2-7B",
    maxTokens: 4096,
    contextWindow: 16384,
    useCases: ["edge","browser","cpu"],
    available: false,
  },
};

/** Per-entry provenance (base, quant_method, attestation, recovery). */
export const ROSO_MODEL_PROVENANCE: Record<string, {
  baseModel: string;
  quantMethod: string;
  phase: string;
  quantizedPath: string | null;
  recoveryDatasets: string[];
  recoveryFinalLoss: number | null;
  packedGB: number | null;
  ram4kGB: number | null;
  ram16kGB: number | null;
  edgeInvariantPassed: boolean;
  iter: number;
  ts: string;
}> = {
  "roso-zamba2-7b": { baseModel: "Zyphra/Zamba2-7B", quantMethod: "bonsai-w1", phase: "A", quantizedPath: "/tmp/roso-smoke-out/sibling-00-Zyphra__Zamba2-7B", recoveryDatasets: [], recoveryFinalLoss: null, packedGB: 1, ram4kGB: 1.2875, ram16kGB: 1.4, edgeInvariantPassed: true, iter: 0, ts: "2026-05-23T11:25:39+00:00" },
};
