// mock-helpers.ts — Shared mock factories for host-sdk tests.

import type { HostImports, AppDef, AuthnContext } from "../src/types.js";

const EMPTY_BYTES = new Uint8Array();

export function createMockAppDef(overrides?: Partial<AppDef>): AppDef {
  return {
    id: "test-app",
    name: "Test App",
    description: "A test application",
    ...overrides,
  };
}

export function createMockHostImports(overrides?: Partial<HostImports>): HostImports {
  const noop = () => {};
  const noopStr = () => "";
  const noopNull = () => null;
  const noopArr = () => "[]";

  return {
    configGet: (_key: string) => undefined,
    logAppend: () => 0n,
    vectorSearch: () => "[]",
    vectorWrite: () => 0,
    vectorCreateIndex: () => "{}",
    clerkVerifyToken: () => EMPTY_BYTES,
    clerkVerifyTokenWithAzp: () => EMPTY_BYTES,
    clerkAuthorize: () => EMPTY_BYTES,
    clerkGetUser: () => EMPTY_BYTES,
    clerkGetOrganization: () => EMPTY_BYTES,
    clerkGetSession: () => EMPTY_BYTES,
    clerkCheckPermission: () => false,
    clerkCheckRole: () => false,
    authnResolveContext: () => null,
    authnVerifyToken: () => EMPTY_BYTES,
    authnEnsureActiveSession: noop,
    authzEnforce: noop,
    cryptoSha256: () => EMPTY_BYTES,
    cryptoSha256Hex: () => "",
    identityRegister: noop,
    identityResolve: () => null,
    identityResolveAddress: () => null,
    identityListActors: () => "[]",
    capabilityDeclare: noop,
    capabilityRevoke: noop,
    capabilityListOwn: () => "[]",
    capabilityAddDependency: noop,
    capabilityRemoveDependency: noop,
    capabilityListDependencies: () => "[]",
    capabilityDiscover: () => "[]",
    dependencyDeclare: noop,
    dependencyRemove: noop,
    dependencyListOwn: () => "[]",
    dependencyCheckAll: () => "{}",
    dependencyCheck: () => "{}",
    dependencyListDependents: () => "[]",
    governanceRegisterManifest: noop,
    governanceCheckPolicy: () => 0 as any,
    rbacDefineRole: noop,
    rbacRemoveRole: noop,
    rbacListRoles: () => "[]",
    rbacAssignRole: noop,
    rbacRevokeRole: noop,
    rbacListUserRoles: () => "[]",
    rbacCheckPermission: () => "{}",
    governanceGetConfig: () => "",
    governanceSetConfig: noop,
    traceabilityLink: noop,
    traceabilityGetChain: () => "[]",
    consentCreate: () => "",
    consentRevoke: noop,
    consentCheck: () => "{}",
    consentList: () => "[]",
    agentRegisterTools: noop,
    agentChat: () => "",
    agentInvokeTool: () => "",
    agentConverse: () => ({ content: "" }),
    agentRoute: () => "",
    agentReact: () => "",
    skillInstall: noop,
    skillUninstall: noop,
    skillListOwn: () => "[]",
    skillGet: () => null,
    skillDiscover: () => "[]",
    skillInvokeTool: () => "",
    invoke: () => EMPTY_BYTES,
    invokeStream: () => ({}),
    createChannel: () => "",
    createProjectConvo: () => "",
    sendProjectMessage: () => "",
    listEnvelopes: () => "[]",
    getThread: () => "{}",
    searchMessages: () => "[]",
    getUnread: () => "{}",
    markRead: noop,
    updatePresence: noop,
    conversationCreateSession: () => "",
    conversationSendMessage: () => "",
    conversationGetHistory: () => "[]",
    conversationGetSession: () => "{}",
    conversationListSessions: () => "[]",
    signalGenerateIdentity: () => EMPTY_BYTES,
    signalGenerateSignedPrekey: () => EMPTY_BYTES,
    signalGenerateOneTimePrekey: () => EMPTY_BYTES,
    signalBuildPreKeyBundle: () => EMPTY_BYTES,
    signalX3dhInitiate: () => EMPTY_BYTES,
    signalX3dhRespond: () => EMPTY_BYTES,
    signalRatchetInitSender: () => EMPTY_BYTES,
    signalRatchetInitReceiver: () => EMPTY_BYTES,
    signalRatchetEncrypt: () => EMPTY_BYTES,
    signalRatchetDecrypt: () => EMPTY_BYTES,
    signalGroupInitSender: () => EMPTY_BYTES,
    signalGroupProcessDistribution: () => EMPTY_BYTES,
    signalGroupEncrypt: () => EMPTY_BYTES,
    signalGroupDecrypt: () => EMPTY_BYTES,
    signalSessionGroupGetOrCreate: () => ({ session: EMPTY_BYTES, distribution: EMPTY_BYTES }),
    signalSessionGroupEncrypt: () => EMPTY_BYTES,
    signalSessionGroupDecrypt: () => EMPTY_BYTES,
    signalSessionGroupAddMember: () => EMPTY_BYTES,
    queryG: () => "[]",
    queryGExec: () => 0n,
    didCreate: () => "",
    didResolve: () => "{}",
    didUpdate: noop,
    didDeactivate: noop,
    didList: () => "[]",
    didRotateKey: () => "",
    didWrite: () => "",
    didUpdateRecord: noop,
    didDeleteRecord: noop,
    followFollow: () => "",
    followUnfollow: noop,
    followSetMuted: noop,
    followListFollowing: () => "[]",
    followListFollowers: () => "[]",
    followCountFollowers: () => 0n,
    followCountFollowing: () => 0n,
    followReact: () => "",
    followUnreact: noop,
    followGetReactions: () => "[]",
    followPullFeed: () => "[]",
    followAckFeed: noop,
    followGetEngagement: () => "{}",
    followLeaderboard: () => "[]",
    followListFollowRequests: () => "[]",
    followApproveFollowRequest: () => "",
    followRejectFollowRequest: noop,
    followApproveAllFollowRequests: () => 0n,
    wGovernanceCheckAccess: () => "{}",
    wGovernanceGetPolicy: () => "{}",
    wGovernanceRegisterPolicy: noop,
    wGovernanceListPolicies: () => "[]",
    wGovernanceRegisterMethodPolicy: noop,
    wGovernanceSetActorSensitivity: noop,
    wGovernanceGetActorSensitivity: () => "public",
    wGovernanceResolveActorVisibility: () => "{}",
    contentLabelCreate: () => "",
    contentLabelQuery: () => "[]",
    contentLabelSetPref: noop,
    contentLabelGetPrefs: () => "{}",
    contentLabelDeclareLabeler: () => "",
    contentLabelGetLabeler: () => "{}",
    contentLabelSubscribe: noop,
    contentLabelUnsubscribe: noop,
    contentLabelListSubscribed: () => "[]",
    smtpConnect: () => ({ provider: "", email: "", displayName: "", connected: false }),
    smtpDisconnect: noop,
    smtpStatus: () => EMPTY_BYTES,
    smtpSendTransactional: () => "",
    ipfsPublish: () => "",
    ipfsPublishUrl: () => "",
    ipfsGatewayUrl: () => "",
    storagePutObject: () => "",
    storageGetObject: () => EMPTY_BYTES,
    storageDeleteObject: noop,
    cdnUpload: () => "",
    cdnFetchUpload: () => "",
    cdnDelete: noop,
    cdnPublicUrl: () => "",
    cdnUploadImage: () => "",
    staticSitePut: () => 0n,
    staticSiteDelete: noop,
    staticSiteListFiles: () => [],
    workflowStart: () => "",
    workflowSignal: noop,
    workflowQuery: () => "{}",
    workflowGet: () => "{}",
    workflowPause: noop,
    workflowResume: noop,
    workflowTerminate: noop,
    workflowPurge: noop,
    workflowRaiseEvent: noop,
    workflowCreateTimer: noop,
    activitySchedule: () => "",
    activityHeartbeat: noop,
    activitySpawnParallel: () => "",
    activityAwaitAll: () => "{}",
    dagSubmit: () => "",
    dagStatus: () => "{}",
    dagCancel: noop,
    timerSet: noop,
    timerCancel: noop,
    timerList: () => "[]",
    reminderSet: noop,
    reminderGet: () => null,
    reminderDelete: noop,
    reminderList: () => "[]",
    actorStateGet: () => null,
    actorStateSet: noop,
    actorStateDelete: noop,
    actorStateList: () => "{}",
    lockTryLock: () => true,
    lockUnlock: noop,
    lockRenew: () => true,
    virtualActorRegister: noop,
    virtualActorInvoke: () => "{}",
    telemetryEmitMetric: noop,
    telemetryStartSpan: () => "",
    telemetryEndSpan: noop,
    telemetryLog: noop,
    accessLogRecord: noop,
    auditEmit: () => 0n,
    auditQuery: () => "[]",
    auditCount: () => 0n,
    ocelEmitEvent: noop,
    ocelQuery: () => "[]",
    anomalyDetect: () => "{}",
    anomalyReport: noop,
    incidentCreate: () => "",
    incidentUpdate: noop,
    incidentResolve: noop,
    incidentGet: () => "{}",
    incidentList: () => "[]",
    pubsubPublish: noop,
    pubsubPull: () => "[]",
    pubsubAck: noop,
    secretsGet: () => null,
    secretsSet: noop,
    secretsDelete: noop,
    vaultGet: () => null,
    vaultPut: noop,
    vaultDelete: noop,
    formsCreate: () => "",
    formsValidate: () => "{}",
    formsGet: () => "{}",
    bpmnDeploy: () => "",
    bpmnStartProcess: () => "",
    bpmnCompleteTask: noop,
    bpmnGetProcess: () => "{}",
    dmnEvaluate: () => "{}",
    dmnDeploy: () => "",
    dm2RegisterPerformer: noop,
    dm2ResolvePerformer: () => null,
    dm2ListPerformers: () => "[]",
    dm2GetParent: () => null,
    dm2ListChildren: () => "[]",
    dm2ListSiblings: () => "[]",
    dm2ListRelationships: () => "[]",
    dm2ListDependencies: () => "[]",
    dm2ResolveLineage: () => "{}",
    contractCreateAgreement: () => "",
    contractGetAgreement: () => "{}",
    contractListAgreements: () => "[]",
    contractRegister: noop,
    contractLookup: () => "[]",
    scraperFetchHtml: () => "",
    scraperExtractText: () => [],
    scraperExtractTable: () => [],
    scraperExtractLinks: () => [],
    scraperExtractAttr: () => [],
    analyzerExtractStructured: () => "{}",
    analyzerAnalyze: () => "",
    automationOpenSession: () => "",
    automationCloseSession: noop,
    automationNavigate: noop,
    automationClick: noop,
    automationTypeText: noop,
    automationSelectOption: noop,
    automationWaitForSelector: noop,
    automationWaitForNavigation: noop,
    automationCurrentUrl: () => "",
    automationPageHtml: () => "",
    automationScreenshot: () => "",
    automationQueryText: () => [],
    automationIsVisible: () => false,
    automationEvalJs: () => "",
    pipelineScrapeAndAnalyze: () => "{}",
    kvGet: () => null,
    kvPut: noop,
    kvDelete: noop,
    kvList: () => "[]",
    r2Get: () => null,
    r2Put: noop,
    r2Delete: noop,
    r2List: () => "[]",
    r2Head: () => null,
    queueSend: noop,
    queueSendBatch: noop,
    walletSign: () => EMPTY_BYTES,
    walletVerify: () => false,
    walletGetAddress: () => "",
    ...overrides,
  };
}

/** Create a mock PDS RPC fetcher that records calls. */
export function createMockPdsRpc(): {
  fetcher: { fetch(input: string | Request, init?: RequestInit): Promise<Response> };
  calls: Array<{ url: string; body: unknown }>;
} {
  const calls: Array<{ url: string; body: unknown }> = [];
  return {
    calls,
    fetcher: {
      async fetch(input: string | Request, init?: RequestInit): Promise<Response> {
        const url = typeof input === "string" ? input : input.url;
        let body: unknown = null;
        if (init?.body) {
          try { body = JSON.parse(init.body as string); } catch { body = init.body; }
        }
        calls.push({ url, body });
        return new Response(JSON.stringify({ ok: true }), {
          status: 200,
          headers: { "content-type": "application/json" },
        });
      },
    },
  };
}
